version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend/job_tracker:/app
    ports:
      - "8000:8000"
    env_file:
      - backend/job_tracker/.env
  frontend:
    build:
      context: .
      dockerfile: frontend/my-react-app/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
